[package]
name = "ql-router"
version = "0.1.0"
edition.workspace = true
publish = false

[features]
default = ["server"]
server = [
    "tokio",
    "dep:anyhow",
    "dep:dashmap",
    "dep:figment",
    "dep:futures-lite",
    "dep:hex",
    "dep:serde",
    "dep:socket2",
    "dep:tracing",
    "dep:tracing-subscriber",
]
tokio = ["dep:tokio"]

[[bin]]
name = "ql-router"
path = "src/main.rs"
required-features = ["server"]

[[test]]
name = "tcp"
required-features = ["server"]

[dependencies]
anyhow = { workspace = true, optional = true }
bytes = "1"
dashmap = { workspace = true, optional = true }
figment = { workspace = true, optional = true }
futures-lite = { version = "2.6", optional = true }
hex = { workspace = true, optional = true }
ql-codec.workspace = true
ql-common.workspace = true
ql-wire.workspace = true
serde = { workspace = true, optional = true }
socket2 = { version = "0.6", optional = true }
tokio = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
