[workspace]
resolver = "2"
members = ["relay-ping-pong", "relay-tui"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
hex = "0.4"
ql-api = { path = "../foundation-api/ql-api" }
ql-codec = { path = "../foundation-api/ql-codec" }
ql-common = { path = "../foundation-api/ql-common" }
ql-fsm = { path = "../foundation-api/ql-fsm" }
ql-relay = { path = "../foundation-api/ql-relay" }
ql-rpc = { path = "../foundation-api/ql-rpc" }
ql-runtime = { path = "../foundation-api/ql-runtime", features = ["rpc"] }
ql-wire = { path = "../foundation-api/ql-wire", features = ["test-utils"] }
tokio = { version = "1", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"] }
