[workspace]
resolver = "2"
members = ["desktop-relay", "foundation-server", "ql-router"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
async-channel = "2"
dashmap = "6"
figment = { version = "0.10", features = ["env"] }
hex = "0.4"
ql-api = { git = "https://github.com/Foundation-Devices/foundation-api.git", branch = "ql-v2-shared-api" }
ql-codec = { git = "https://github.com/Foundation-Devices/foundation-api.git", branch = "ql-v2-shared-api" }
ql-common = { git = "https://github.com/Foundation-Devices/foundation-api.git", branch = "ql-v2-shared-api" }
ql-fsm = { git = "https://github.com/Foundation-Devices/foundation-api.git", branch = "ql-v2-shared-api" }
ql-router = { path = "ql-router" }
ql-runtime = { git = "https://github.com/Foundation-Devices/foundation-api.git", branch = "ql-v2-shared-api", features = ["rpc"] }
ql-wire = { git = "https://github.com/Foundation-Devices/foundation-api.git", branch = "ql-v2-shared-api", features = ["test-utils"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }

[patch."https://github.com/Foundation-Devices/foundation-api.git"]
ql-codec = { path = "../foundation-api/ql-codec" }
