[package]
name = "relay-ping-pong"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
bytes = "1"
hex.workspace = true
ql-codec.workspace = true
ql-common.workspace = true
ql-fsm.workspace = true
ql-relay.workspace = true
ql-rpc.workspace = true
ql-runtime.workspace = true
ql-wire.workspace = true
tokio.workspace = true
