[package]
name = "relay-ping-pong"
version = "0.1.0"
edition.workspace = true
publish = false

[features]
default = ["server"]
server = [
    "tokio",
    "dep:anyhow",
    "dep:dashmap",
    "dep:figment",
    "dep:futures-lite",
    "dep:hex",
    "dep:serde",
    "dep:socket2",
    "dep:tracing",
    "dep:tracing-subscriber",
]
tokio = ["dep:tokio"]

[[bin]]
name = "ql-router"
path = "src/main.rs"
required-features = ["server"]

[[test]]
name = "tcp"
required-features = ["server"]

[dependencies]
anyhow = { workspace = true, optional = true }
bytes = "1"
hex.workspace = true
ql-codec.workspace = true
ql-common.workspace = true
ql-fsm.workspace = true
ql-relay.workspace = true
ql-rpc.workspace = true
ql-runtime.workspace = true
ql-wire.workspace = true
tokio.workspace = true
