[package]
name = "foundation-server"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
dashmap.workspace = true
figment.workspace = true
hex.workspace = true
ql-api.workspace = true
ql-codec.workspace = true
ql-common.workspace = true
ql-fsm.workspace = true
ql-keyos = { git = "https://github.com/Foundation-Devices/foundation-api.git", rev = "00f74e6df83cc44642262a0089722b04cdcf963f" }
ql-rpc.workspace = true
ql-router.workspace = true
ql-runtime = { workspace = true, features = ["rpc"] }
ql-wire.workspace = true
serde.workspace = true
sha2 = "0.10"
tokio.workspace = true
